vti_encoding:SR|utf8-nl
vti_timelastmodified:TR|13 Nov 2010 19:42:25 -0000
vti_extenderversion:SR|5.0.2.6790
vti_cacheddtm:TX|13 Nov 2010 19:42:25 -0000
vti_filesize:IR|5297
vti_cachedtitle:SR|SQL Web Interface
vti_cachedbodystyle:SR|<body align=center>
vti_cachedlinkinfo:VX|S|./../website/tmcDevelopment/rcstri.js S|SqlAJAX.js
vti_cachedsvcrellinks:VX|FSUS|website/tmcDevelopment/rcstri.js FSUS|sqlWebI/SqlAJAX.js
vti_cachedneedsrewrite:BR|false
vti_cachedhasbots:BR|false
vti_cachedhastheme:BR|false
vti_cachedhasborder:BR|false
vti_charset:SR|windows-1252
vti_title:SR|SQL Web Interface
vti_lineageid:SR|{3DD9410F-5439-48A9-ABF8-EBFA0DE0BAA1}
vti_backlinkinfo:VX|
